const SignupLang = {
  English: {
    signIn: "Sign In",
    s1h1p1: "Unlimited movies,",
    s1h1p2: "TV shows and more",
    s1h3: "Starts at ₹149. Cancel anytime.",
    s1h5: "Ready to watch? Enter your email to create or restart your membership.",
    s1InPlaceholder1: "Email Address",
    s1Button1: "Get Started >",
    preCardH1: "Plans to suit your needs and your budget",
    preCardH3: "Enjoy Netflix starting at just ₹149.",
    cardH2: "More reasons to join",
    card1h3: " Enjoy on your TV",
    card1p:
      " Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.",
    card2h3: "Download your shows to watch offline",
    card2p: "Save your favourites easily and always have something to watch.",
    card3h3: "Watch everywhere",
    card3p:
      "Stream unlimited movies and TV shows on your phone, tablet, laptop and TV.",
    card4h3: "Create profiles for kids",
    card4p:
      "Send kids on adventures with their favourite characters in a space made just for them — free with your membership.",
    carouH2: "Frequently Asked Questions",
    footerH5: "Questions? Call",
    footerSpan: " 000-800-919-1694",
    footerGrid1: "FAQ",
    footerGrid2: "Help Centre",
    footerGrid3: "Account",
    footerGrid4: "Media Centre",
    footerGrid5: "Investor Relations",
    footerGrid6: "Jobs",
    footerGrid7: "Ways to Watch",
    footerGrid8: "Terms of Use",
    footerGrid9: "Privacy",
    footerGrid10: "Cookie Preferences",
    footerGrid11: "Corporate Information",
    footerGrid12: "Contact Us",
    footerGrid13: "Speed Test",
    footerGrid14: "Legal Notice",
    footerGrid15: "Only on Netflix",
    footerLastH5: "Netflix India",
  },
  Bengali: {
    signIn: "সাইন ইন",
    s1h1p1: "​সীমাহীন চলচ্চিত্র,",
    s1h1p2: "টিভি শো এবং আরো",
    s1h3: "​₹149 থেকে শুরু। যেকোনো সময় বাতিল করুন।",
    s1h5: "দেখার জন্য প্রস্তুত? আপনার সদস্যতা তৈরি বা পুনরায় চালু করতে আপনার Email লিখুন.",
    s1InPlaceholder1: "ইমেল ঠিকানা",
    s1Button1: "এবার শুরু >",
    preCardH1: "আপনার চাহিদা এবং আপনার বাজেট অনুসারে পরিকল্পনা",
    preCardH3: "মাত্র ₹149 থেকে শুরু করে Netflix উপভোগ করুন।",
    cardH2: "যোগদানের আরও কারণ",
    card1h3: "আপনার টিভিতে উপভোগ করুন",
    card1p:
      "Smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players এবং আরও অনেক কিছুতে দেখুন।",
    card2h3: "অফলাইনে দেখতে আপনার শো ডাউনলোড করুন",
    card2p:
      "আপনার পছন্দগুলি সহজেই সংরক্ষণ করুন এবং সর্বদা দেখার জন্য কিছু থাকে৷",
    card3h3: "সর্বত্র দেখুন",
    card3p:
      "আপনার ফোন, ট্যাবলেট, ল্যাপটপ এবং টিভিতে সীমাহীন সিনেমা এবং টিভি শো স্ট্রিম করুন।",
    card4h3: "বাচ্চাদের জন্য প্রোফাইল তৈরি করুন",
    card4p:
      "বাচ্চাদের অ্যাডভেঞ্চারে তাদের প্রিয় চরিত্রের সাথে তাদের জন্য তৈরি করা জায়গায় পাঠান — আপনার সদস্যতার সাথে বিনামূল্যে।",
    carouH2: "প্রায়শই জিজ্ঞাসিত প্রশ্ন",
    footerH5: "প্রশ্ন? কল করুন",
    footerSpan: " 000-800-919-1694",
    footerGrid1: "FAQ",
    footerGrid2: "সহায়তা কেন্দ্র",
    footerGrid3: "হিসাব",
    footerGrid4: "মিডিয়া কেন্দ্র",
    footerGrid5: "বিনিয়োগকারী সম্পর্ক",
    footerGrid6: "চাকরি",
    footerGrid7: "দেখার উপায়",
    footerGrid8: "ব্যবহারের শর্তাবলী",
    footerGrid9: "গোপনীয়তা",
    footerGrid10: "কুকি পছন্দ",
    footerGrid11: "কর্পোরেট তথ্য",
    footerGrid12: "যোগাযোগ করুন",
    footerGrid13: "গতি পরীক্ষা",
    footerGrid14: "আইনি নোটিশ",
    footerGrid15: "শুধুমাত্র Netflix এ",
    footerLastH5: "Netflix ভারত",
  },
  Hindi: {
    signIn: "साइन इन करें",
    s1h1p1: "असीमित फिल्में,",
    s1h1p2: "टीवी शो और भी बहुत कुछ",
    s1h3: "₹149 से शुरू। किसी भी समय रद्द करें.",
    s1h5: "देखने के लिए तैयार हैं? अपनी सदस्यता बनाने या पुनः आरंभ करने के लिए अपना Email दर्ज करें।",
    s1InPlaceholder1: "ई-मेल पता",
    s1Button1: "आरंभ करें >",
    preCardH1: "आपकी आवश्यकताओं और आपके बजट के अनुरूप योजनाएं",
    preCardH3: "महज़ ₹149 से शुरू होकर Netflix का आनंद लें।",
    cardH2: "शामिल होने के और भी कारण",
    card1h3: "अपने टीवी पर आनंद लें",
    card1p:
      "स्मार्ट टीवी, PlayStation, Xbox, Chromecast, Apple TV, ब्लू-रे प्लेयर और बहुत कुछ पर देखें।",
    card2h3: "ऑफ़लाइन देखने के लिए अपने शो डाउनलोड करें",
    card2p:
      "अपने पसंदीदा को आसानी से सहेजें और हमेशा देखने के लिए कुछ न कुछ रखें।",
    card3h3: "हर जगह नजर रखें",
    card3p:
      "अपने फोन, टैबलेट, लैपटॉप और टीवी पर असीमित फिल्में और टीवी शो स्ट्रीम करें।",
    card4h3: "बच्चों के लिए प्रोफ़ाइल बनाएं",
    card4p:
      "बच्चों को केवल उनके लिए बनाई गई जगह में उनके पसंदीदा पात्रों के साथ साहसिक यात्रा पर भेजें - आपकी सदस्यता के साथ निःशुल्क।",
    carouH2: "अक्सर पूछे जाने वाले प्रश्नों",
    footerH5: "प्रशन? पुकारना",
    footerSpan: " 000-800-919-1694",
    footerGrid1: "FAQ",
    footerGrid2: "सहायता केंद्र",
    footerGrid3: "खाता",
    footerGrid4: "मीडिया केंद्र",
    footerGrid5: "निवेशक संबंध",
    footerGrid6: "नौकरियां",
    footerGrid7: "देखने के तरीके",
    footerGrid8: "उपयोग की शर्तें",
    footerGrid9: "गोपनीयता",
    footerGrid10: "कुकी प्राथमिकताएँ",
    footerGrid11: "कॉर्पोरेट जानकारी",
    footerGrid12: "संपर्क करें",
    footerGrid13: "गति परीक्षण",
    footerGrid14: "कानूनी नोटिस",
    footerGrid15: "केवल Netflix पर",
    footerLastH5: "Netflix भारत",
  },
};

export default SignupLang;
